
spring:
  r2dbc:
    url: r2dbc:mysql://mysql-franquicia.c5m0qsoac3uj.us-east-2.rds.amazonaws.com:3306/franquicias_db
    username: root
    password: SetiTest987

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysql-franquicia.c5m0qsoac3uj.us-east-2.rds.amazonaws.com:3306/franquicias_db
    user: root
    password: SetiTest987 

  server:
    port: 9008 
    